# AutoGenerated File 
#
# You can edit this file if you feel comfortable.

# AutoGenerated File 
#
# You can edit this file if you feel comfortable.


gulp       = require 'gulp'
coffee     = require 'gulp-coffee'
nodemon    = require 'gulp-nodemon'
shellexec  = require('child_process').exec
exec       = require 'gulp-exec'
mocha      = require 'gulp-mocha'
changed    = require 'gulp-changed'

project =
    paths :
        coffee   : 'src/main/coffee/**/*.coffee'
        js       : 'src/main/js/**/*.js'
        test     : 'src/test/coffee/**/*.coffee'
        res      : 'src/main/resources/**/*'
        build    : 'src/build/docker/**/*'
        dest     : 'target'

gulp.task 'clean', ->
    gulp.src 'target/**/**'
        .pipe exec 'rm -rf target/*', {}

gulp.task 'coffee', ->
    gulp.src project.paths.coffee
       .pipe changed 'target'
       .pipe coffee bare: yes
       .pipe gulp.dest 'target'

gulp.task 'js', ['coffee'], ->
    gulp.src project.paths.js
       .pipe changed gulp.dest 'target'

gulp.task 'res', ['js'], ->
    gulp.src 'src/main/resources/**/*'
       .pipe changed gulp.dest 'target'

gulp.task 'test:compile', ['res'], ->
    gulp.src project.paths.test
        .pipe changed coffeeES6 bare : yes
        .pipe gulp.dest 'target'

gulp.task 'test:run', ['test:compile'], ->
    gulp.src 'target/db-resource-test.js'
        .pipe mocha 
            reporter: 'spec',
            globals:
                should: require 'should'
        .once 'end', ->
            process.exit()

gulp.task 'watch', ['res'], ->
     gulp.watch project.paths.coffee, ['coffee']
     gulp.watch project.paths.js, ['js']
     gulp.watch project.paths.res, ['res']
     
gulp.task 'run', ['res'], (cb) ->
    shellexec 'node target/main.js', (err, stdout, stderr) ->
        console.log stdout
        console.error stderr
        cb err
        
gulp.task 'server', ['watch'], ->
  nodemon
    script: 'target/main.js'
    nodeArgs: ['--harmony']

gulp.task 'default', ['server']